spring.application.name=backend


# Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=cdg
spring.datasource.password=cdg123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Server
server.port=8080


# JWT
jwt.secret=MySuperSecretKeyForJwtAuthentication123456789
jwt.expiration=3600000